package com.tts.easyvoice
object SampleTexts {
    private val map = mapOf(
        "eng" to "This is a sample of text spoken in English.",
        "spa" to "Esta es una muestra de texto hablado en español.",
        "fra" to "Ceci est un échantillon de texte parlé en français.",
        "deu" to "Dies ist ein Beispieltext in deutscher Sprache.",
        "ita" to "Questo è un esempio di testo parlato in italiano.",
        "por" to "Esta é uma amostra de texto falado em português.",
        "rus" to "Это образец текста, произнесенного на русском языке.",
        "nld" to "Dit is een voorbeeld van tekst gesproken in het Nederlands.",
        "swe" to "Detta är ett textprov talat på svenska.",
        "pol" to "To jest próbka tekstu mówionego w języku polskim.",
        "ell" to "Αυτό είναι ένα δείγμα κειμένου που ομιλείται στα ελληνικά.",
        "hin" to "यह हिंदी में बोले गए पाठ का एक नमूना है।",
        "zho" to "这是用中文说的文本样本。",
        "jpn" to "これは日本語で話されたテキストのサンプルです。",
        "kor" to "이것은 한국어로 된 텍스트의 샘플입니다.",
        "ara" to "هذه عينة من نص منطوق باللغة العربية.",
        "heb" to "זוהי דוגמה לטקסט מדובר בעברית.",
        "tur" to "Bu, Türkçe konuşulmuş bir metin örneğidir.",
        "tha" to "นี่คือตัวอย่างข้อความที่พูดเป็นภาษาไทย",
        "vie" to "Đây là một đoạn văn bản mẫu được nói bằng tiếng Việt Nam.",
        "ben" to "এটি বাংলা ভাষায় কথ্য পাঠ্যের একটি নমুনা।",
        "urd" to "یہ اردو میں بولے گئے متن کا ایک نمونہ ہے۔",
        "fas" to "این یک نمونه از متن گفتاری به زبان فارسی است.",
        "ind" to "Ini adalah contoh teks yang diucapkan dalam bahasa Indonesia.",
        "fin" to "Tämä on suomeksi puhuttu tekstinäyte.",
        "hun" to "Ez egy minta a magyar nyelven beszélt szövegből.",
        "ces" to "Toto je vzorek textu mluveného v češtině.",
        "slk" to "Toto je vzorka textu hovoreného v slovenčine.",
        "ron" to "Acesta este un eșantion de text vorbit în română.",
        "ukr" to "Це зразок тексту, вимовленого українською мовою.",
        "gle" to "Seo sampla de théacs labhartha i nGaeilge.",
        "isl" to "Þetta er sýnishorn af texta talað á íslensku.",
        "est" to "See on eesti keeles räägitud teksti näidis.",
        "lav" to "Šis ir latviešu valodā runāta teksta paraugs.",
        "lit" to "Tai pavyzdys teksto, kalbamo lietuvių kalba.",
        "hrv" to "Ovo je uzorak teksta govorenog na hrvatskom jeziku.",
        "srp" to "Ово је узорак текста говореног на српском језику.",
        "slv" to "To je vzorec besedila, govorjenega v slovenščini.",
        "bos" to "Ovo je primjer teksta govorenog na bosanskom jeziku.",
        "mkd" to "Ова е примерок на текст зборуван на македонски јазик.",
        "bul" to "Това е примерен текст, изговорен на български език.",
        "nno" to "Dette er ein prøve på tekst tala på nynorsk.",
        "nob" to "Dette er en prøve på tekst talt på bokmål.",
        "cat" to "Això és un exemple de text parlat en català.",
        "eus" to "Hau euskaraz hitz egiten den testuaren adibidea da.",
        "glg" to "Este é un exemplo de texto falado en galego.",
        "tel" to "ఇది తెలుగులో మాట్లాడిన వచనానికి నమూనా.",
        "tam" to "இது தமிழில் பேசப்பட்ட உரைக்கான மாதிரி.",
        "kan" to "ಇದು ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿದ ಪಠ್ಯದ ಒಂದು ಮಾದರಿ.",
        "pan" to "ਇਹ ਪੰਜਾਬੀ ਵਿੱਚ ਬੋਲਿਆ ਗਿਆ ਪਾਠ ਦਾ ਇੱਕ ਨਮੂਨਾ ਹੈ।",
        "nep" to "यो नेपालीमा बोलिएको पाठको नमूना हो।",
        "mal" to "ഇത് മലയാളത്തിൽ സംസാരിക്കുന്ന ഒരു വാചകത്തിന്റെ മാതൃകയാണ്.",
        "mar" to "हा मराठीत बोलल्या गेलेल्या मजकुराचा नमुना आहे.",
        "guj" to "આ ગુજરાતીમાં બોલાયેલા ટેક્સ્ટનું નમૂનું છે.",
        "sin" to "මෙය සිංහල භාෂාවෙන් කථනය කළ පාඨයක ආදර්ශයකි.",
        "ori" to "ଏହା ଓଡ଼ିଆରେ କଥିତ ପାଠର ଏକ ନମୁନା।",
        "swa" to "Huu ni mfano wa maandishi yaliyozungumzwa kwa Kiswahili.",
        "zul" to "Lesi isampula sombhalo okhulunywe ngesiZulu.",
        "amh" to "ይህ በአማርኛ የተነገረ የጽሑፍ ናሙና ነው።",
        "yor" to "Eyi jẹ apẹẹrẹ ti ọrọ ti a sọ ni èdè Yorùbá.",
        "ibo" to "Nke a bụ ihe atụ nke okwu a na-asụ n'asụsụ Igbo.",
        "hau" to "Wannan misali ne na rubutun da ake magana a cikin Hausa.",
        "xho" to "Esi sisampula sombhalo othethwayo ngesiXhosa.",
        "som" to "Tani waa tusaale ahaan qoraalka lagu hadlay af Soomaali.",
        "orm" to "Kun fakkeenya barruu afaan Oromoo ta'uun dubbifamu.",
        "msa" to "Ini ialah contoh teks yang dituturkan dalam bahasa Melayu.",
        "tgl" to "Ito ay isang halimbawa ng teksto na sinasalita sa Tagalog.",
        "mon" to "Энэ бол Монгол хэлээр ярьсан текстийн жишээ юм.",
        "khm" to "នេះគឺជាគំរូនៃអត្ថបទដែលនិយាយជាភាសាខ្មែរ។",
        "lao" to "ນີ້ແມ່ນຕົວຢ່າງຂອງຂໍ້ຄວາມທີ່ເວົ້າເປັນພາສາລາວ.",
        "mya" to "ဤသည်မှာ မြန်မာဘာသာဖြင့် ပြောဆိုထားသော စာသားနမူနာတစ်ခုဖြစ်သည်။",
        "kaz" to "Бұл қазақ тілінде сөйленген мәтіннің үлгісі.",
        "uzb" to "Bu o'zbek tilida so'zlashgan matn namunasi.",
        "kir" to "Бул кыргыз тилинде сүйлөнгөн тексттин үлгүсү.",
        "tuk" to "Bu türkmen dilinde gürlenýän tekstiň mysalydyr.",
        "mri" to "He tauira tēnei o te kōrero i te reo Māori.",
        "haw" to "He laʻana kēia o ka ʻōlelo i ka ʻōlelo Hawaiʻi.",
        "smo" to "O lenei o se faʻataʻitaʻiga o le tautala i le gagana Sāmoa.",
        "ton" to "Ko e fakataʻitaʻi ʻeni ʻo e lea faka-Tonga.",
        "alb" to "Kjo është një shembull i tekstit të folur në gjuhën shqipe.",
        "aze" to "Bu, Azərbaycan dilində danışılmış mətn nümunəsidir.",
        "kur" to "Ev nimûneyek ji nivîsê ye ku bi zimanê Kurdî tê axaftin.",
        "pas" to "دا په پښتو ژبه کې د ویل شوي متن یوه نمونه ده.",
        "sot" to "Sena ke mohlala wa mongolo o buuoang ka Sesotho.",
        "asm" to "এয়া অসমীয়া ভাষাত কোৱা এটা পাঠৰ নমুনা।",
        "sun" to "Ieu mangrupikeun conto teks anu diucapkeun dina basa Sunda.",
        "kok" to "हें कोंकणीन उलयिल्ल्या पाठाचो एक नमुनो आसा।",
        "sqi" to "Kjo është një shembull i tekstit të folur në gjuhën shqipe.",
        "mai" to "ई मैथिली में बाजल गेल पाठक एक नमूना अछि।",
        "cmn" to "这是用普通话说的文本样本。",
        "sat" to "नोवा दो सान्ताड़ी ते रोड़ आकान ओलोक् रेनाक् मित् आदोर काना।",
        "snd" to "هيءَ سنڌي ۾ ڳالهائي وئي ٽيڪسٽ جو هڪ نمونو آهي.",
        "kas" to "یہ کاشُر زَبان مَنٛز وَنَل گَے ٹیکسٹُک اَکھ نَمونہ چھُ۔",
        "mni" to "মসি মৈতৈলোন্দা ঙাংখিবা ৱাহৈ পরেংগী খুদম অমনি।",
        "san" to "अयं संस्कृतभाषायां कथितस्य पाठस्य एकं उदाहरणम् अस्ति।",
        "brx" to "बे बर' राव गासैनि सोदोब फरायलाइनि मोनसे बिदिन्थि।",
        "doi" to "एह् डोगरी च बोले गेदे पाठ दा इक नमूना ऐ।",
        "jav" to "Iki conto teks sing diucapake ing basa Jawa.",
        "jv" to "Iki conto teks sing diucapake ing basa Jawa.",
        "yue" to "呢個係用粵語講嘅文字樣本。",
        "cym" to "Dyma enghraifft o destun yn cael ei siarad yn Gymraeg.",
        "cy" to "Dyma enghraifft o destun yn cael ei siarad yn Gymraeg.",
        "dan" to "Dette er en prøve af tekst talt på dansk.",
        "da" to "Dette er en prøve af tekst talt på dansk.",
        "fil" to "Ito ay isang halimbawa ng teksto na sinasalita sa Filipino.",
        "lat" to "Hoc exemplum textus lingua Latina locuti est.",
        "la" to "Hoc exemplum textus lingua Latina locuti est.",
        "afr" to "Dit is 'n voorbeeld van teks wat in Afrikaans gepraat word.",
        "af" to "Dit is 'n voorbeeld van teks wat in Afrikaans gepraat word.",
        "hye" to "Սա հայերենով խոսված տեքստի նմուշ է։",
        "hy" to "Սա հայերենով խոսված տեքստի նմուշ է։",
        "hyw" to "Այս արեւմտահայերէնով խօսուած տեքստի նմուշ է։",
        "kat" to "ეს არის ქართულად ნათქვამი ტექსტის ნიმუში.",
        "ka" to "ეს არის ქართულად ნათქვამი ტექსტის ნიმუში.",
        "ltz" to "Dëst ass e Beispill vun Text dee Lëtzebuergesch geschwat gëtt.",
        "lb" to "Dëst ass e Beispill vun Text dee Lëtzebuergesch geschwat gëtt.",
        "mlt" to "Dan huwa kampjun ta' test mitkellem bil-Malti.",
        "mt" to "Dan huwa kampjun ta' test mitkellem bil-Malti.",
        "oci" to "Aquò es un exemple de tèxte parlat en occitan.",
        "oc" to "Aquò es un exemple de tèxte parlat en occitan.",
        "bre" to "Setu ur skouer eus testenn komzet e brezhoneg.",
        "br" to "Setu ur skouer eus testenn komzet e brezhoneg.",
        "ina" to "Isto es un exemplo de texto parlate in interlingua.",
        "ia" to "Isto es un exemplo de texto parlate in interlingua.",
        "epo" to "Ĉi tio estas specimeno de teksto parolata en Esperanto.",
        "eo" to "Ĉi tio estas specimeno de teksto parolata en Esperanto.",
        "tgk" to "Ин намунаи матни бо забони тоҷикӣ гуфташуда аст.",
        "tg" to "Ин намунаи матни бо забони тоҷикӣ гуфташуда аст.",
        "bel" to "Гэта ўзор тэксту, прамоўленага на беларускай мове.",
        "be" to "Гэта ўзор тэксту, прамоўленага на беларускай мове.",
        "gla" to "Seo eisimpleir de theacsa air a bhruidhinn ann an Gàidhlig.",
        "gd" to "Seo eisimpleir de theacsa air a bhruidhinn ann an Gàidhlig.",
        "ga" to "Seo sampla de théacs labhartha i nGaeilge.",
        "tat" to "Бу татар телендә сөйләнгән текст үрнәге.",
        "tt" to "Бу татар телендә сөйләнгән текст үрнәге.",
        "chr" to "ᎯᎠ ᎤᎵᎮᎵᏍᏗ ᏗᎧᏃᎩᏍᏗ ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ ᏂᎨᏒᎾ ᎨᏒ.",
        "yid" to "דאָס איז אַ מוסטער פון טעקסט גערעדט אין ייִדיש.",
        "yi" to "דאָס איז אַ מוסטער פון טעקסט גערעדט אין ייִדיש.",
        "fry" to "Dit is in foarbyld fan tekst sprutsen yn it Frysk.",
        "fy" to "Dit is in foarbyld fan tekst sprutsen yn it Frysk.",
        "uig" to "بۇ ئۇيغۇر تىلىدا سۆزلەنگەن تېكىستنىڭ بىر ئۈلگىسى.",
        "ug" to "بۇ ئۇيغۇر تىلىدا سۆزلەنگەن تېكىستنىڭ بىر ئۈلگىسى.",
        "sw" to "Huu ni mfano wa maandishi yaliyozungumzwa kwa Kiswahili.",
        "so" to "Tani waa tusaale ahaan qoraalka lagu hadlay af Soomaali.",
        "am" to "ይህ በአማርኛ የተነገረ የጽሑፍ ናሙና ነው።",
        "ha" to "Wannan misali ne na rubutun da ake magana a cikin Hausa.",
        "yo" to "Eyi jẹ apẹẹrẹ ti ọrọ ti a sọ ni èdè Yorùbá.",
        "zu" to "Lesi isampula sombhalo okhulunywe ngesiZulu.",
        "ig" to "Nke a bụ ihe atụ nke okwu a na-asụ n'asụsụ Igbo.",
        "om" to "Kun fakkeenya barruu afaan Oromoo ta'uun dubbifamu.",
        "lug" to "Kino kye kyakulabirako ky'ebigambo ebyogeddwa mu Luganda.",
        "lg" to "Kino kye kyakulabirako ky'ebigambo ebyogeddwa mu Luganda.",
        "wol" to "Lii mooy misaal bu benn mbind bu ñuy wax ci wolof.",
        "wo" to "Lii mooy misaal bu benn mbind bu ñuy wax ci wolof.",
        "kin" to "Uru ni urugero rw'inyandiko ivugwa mu Kinyarwanda.",
        "rw" to "Uru ni urugero rw'inyandiko ivugwa mu Kinyarwanda.",
        "sna" to "Ichi chitsanzo chemutauro unotaurwa muchiShona.",
        "sn" to "Ichi chitsanzo chemutauro unotaurwa muchiShona.",
        "lin" to "Oyo ezali ndakisa ya makomi oyo elobi na lingála.",
        "ln" to "Oyo ezali ndakisa ya makomi oyo elobi na lingála.",
        "mlg" to "Ity dia ohatra amin'ny lahatsoratra miteny amin'ny teny Malagasy.",
        "mg" to "Ity dia ohatra amin'ny lahatsoratra miteny amin'ny teny Malagasy.",
        "ewe" to "Esia nye kpɔɖeŋu aɖe si wogblɔ le Eʋegbe me.",
        "ee" to "Esia nye kpɔɖeŋu aɖe si wogblɔ le Eʋegbe me.",
        "aka" to "Eyi yɛ nsɛm a wɔka no wɔ Twi kasa mu ho nhwɛso.",
        "ak" to "Eyi yɛ nsɛm a wɔka no wɔ Twi kasa mu ho nhwɛso.",
        "nso" to "Se ke mohlala wa sengwalwa seo se boletšwego ka Sepedi.",
        "tsn" to "Se ke sekao sa mokwalo o o buiwang ka Setswana.",
        "tn" to "Se ke sekao sa mokwalo o o buiwang ka Setswana.",
        "xh" to "Esi sisampula sombhalo othethwayo ngesiXhosa.",
        "nde" to "Lesi yisibonelo sombhalo okhulunywayo ngesiNdebele.",
        "nd" to "Lesi yisibonelo sombhalo okhulunywayo ngesiNdebele.",
        "bam" to "Nin ye sɛbɛnni misali ye min bɛ fɔ bamanankan na.",
        "bm" to "Nin ye sɛbɛnni misali ye min bɛ fɔ bamanankan na.",
        "que" to "Kayqa qichwa simipi rimashqa qillqap huknin rikch'aqnin.",
        "qu" to "Kayqa qichwa simipi rimashqa qillqap huknin rikch'aqnin.",
        "grn" to "Ko ha'e peteĩ techapyrã ñe'ẽ ojepurúva guaraníme.",
        "gn" to "Ko ha'e peteĩ techapyrã ñe'ẽ ojepurúva guaraníme.",
        "aym" to "Aka aymara arunxa arsuña qillqata uñacht'ayañatakiwa.",
        "bod" to "འདི་ནི་བོད་སྐད་དུ་སྨྲས་པའི་ཡི་གེའི་དཔེ་མཚོན་ཞིག་ཡིན།",
        "bo" to "འདི་ནི་བོད་སྐད་དུ་སྨྲས་པའི་ཡི་གེའི་དཔེ་མཚོན་ཞིག་ཡིན།",
        "dzo" to "འ་ནི་རྫོང་ཁ་ནང་ལབ་མི་ཡིག་ཆ་གི་དཔེ་ཨིན།",
        "dz" to "འ་ནི་རྫོང་ཁ་ནང་ལབ་མི་ཡིག་ཆ་གི་དཔེ་ཨིན།",
        "my" to "ဤသည်မှာ မြန်မာဘာသာဖြင့် ပြောဆိုထားသော စာသားနမူနာတစ်ခုဖြစ်သည်။",
        "lo" to "ນີ້ແມ່ນຕົວຢ່າງຂອງຂໍ້ຄວາມທີ່ເວົ້າເປັນພາສາລາວ.",
        "tir" to "እዚ ብትግርኛ ዝተዛረበ ጽሑፍ ኣብነት እዩ።",
        "ti" to "እዚ ብትግርኛ ዝተዛረበ ጽሑፍ ኣብነት እዩ።",
        "bpy" to "এহান বিষ্ণুপ্রিয়া মণিপুরী ঠারর কথা মাতেসি পাঠর নমুনা।",
        "kk" to "Бұл қазақ тілінде сөйленген мәтіннің үлгісі.",
        "ky" to "Бул кыргыз тилинде сүйлөнгөн тексттин үлгүсү.",
        "tk" to "Bu türkmen dilinde gürlenýän tekstiň mysalydyr.",
        "shn" to "ၼႆႉပဵၼ် တူဝ်ယၢင်ႇ လိၵ်ႈတႆး ဝႃႈ တႆးတႃႇ။",
        "grc" to "Τοῦτό ἐστι παράδειγμα τοῦ λόγου τοῦ λεγομένου ἑλληνιστί.",
        "hat" to "Sa a se yon echantiyon tèks ki pale nan kreyòl ayisyen.",
        "ht" to "Sa a se yon echantiyon tèks ki pale nan kreyòl ayisyen.",
        "kal" to "Una kalaallisut oqaasiitigut oqaluttup assersuutaavoq.",
        "kl" to "Una kalaallisut oqaasiitigut oqaluttup assersuutaavoq.",
        "pap" to "Esaki ta un ehèmpel di teksto papiá na Papiamentu.",
        "jbo" to "ti mupli lo lerpoi poi se cusku bau la lojban.",
        "nci" to "Inin se tlanauatilkayotl tlen motoa ika nauatl.",
        "arg" to "Isto ye un eixemplo de testo charrau en aragonés.",
        "an" to "Isto ye un eixemplo de testo charrau en aragonés.",
        "quc" to "We jun k'utb'al tzij pa ri ch'ab'al K'iche'.",
        "lfn" to "Esta es un esemplo de testo parlada en Lingua Franca Nova.",
        "cor" to "Hemm yw ensampel a destenn kewsys yn kernewek.",
        "kw" to "Hemm yw ensampel a destenn kewsys yn kernewek.",
        "glv" to "Shoh sampleyr jeh teks loayrit ayns Gaelg.",
        "gv" to "Shoh sampleyr jeh teks loayrit ayns Gaelg.",
        "oss" to "Ай фӕткъуы ирон ӕвзагыл дзургӕ тексты.",
        "os" to "Ай фӕткъуы ирон ӕвзагыл дзургӕ тексты.",
        "che" to "Хӏара нохчийн маттахь дийцина йозанан масал ду.",
        "ce" to "Хӏара нохчийн маттахь дийцина йозанан масал ду.",
        "chv" to "Ку чӑваш чӗлхипе калакан текстӑн тӗслӗхӗ.",
        "cv" to "Ку чӑваш чӗлхипе калакан текстӑн тӗслӗхӗ.",
        "sme" to "Dát lea ovdamearka teavsttas mii hállojuvvo davvisámegillii.",
        "se" to "Dát lea ovdamearka teavsttas mii hállojuvvo davvisámegillii.",
        "smn" to "Taat lii ovdâmerkkâ tekstâst mii sárnojuvvoo anarâškielân.",
        "fao" to "Hetta er eitt dømi um tekst tosaðan á føroyskum.",
        "fo" to "Hetta er eitt dømi um tekst tosaðan á føroyskum.",
        "roh" to "Quai è in exempel dad in text discurrì en rumantsch.",
        "rm" to "Quai è in exempel dad in text discurrì en rumantsch.",
        "scn" to "Chistu è nu esempiu di testu parratu 'n sicilianu.",
        "sc" to "Quistu est unu esèmpiu de testu faeddadu in sardu.",
        "vec" to "Questo xe un esempio de testo parlà in vèneto.",
        "lij" to "Questo o l'é un exempio de testo parlou in ligure.",
        "lmo" to "Chest l'è un esempi de test parlaa in lombard.",
        "nds" to "Dit is en Bispeel vun Text, de op Plattdüütsch snackt warrt.",
        "wln" to "Çoula est-st on egzimpe di tecse cåzé e walon.",
        "wa" to "Çoula est-st on egzimpe di tecse cåzé e walon.",
        "gsw" to "Des esch e Beispiel vun Tekscht wo uf Elsassisch gschwätzt werd.",
        "als" to "Das isch es Biispil vo Text wo uf Schwizerdütsch gredt wird.",
        "bar" to "Des is a Beispui vo am Text auf Boarisch.",
        "hsb" to "To je přikład teksta rěčaneho w hornjoserbšćinje.",
        "dsb" to "To jo pśikład teksta powědanego w dolnoserbšćinje.",
        "szl" to "To je bajszpil tekstu godanygo we ślůnskij godce.",
        "ckb" to "ئەمە نموونەیەکی دەقی قسەکراوە بە کوردی سۆرانی.",
        "ast" to "Esti ye un exemplu de testu faláu n'asturianu.",
        "sah" to "Бу саха тылынан этиллибит тиэкис холобура.",
        "prg" to "Sta ast ainā prūsiskan bilātan tekstan.",
        "tpi" to "Dispela em wanpela eksampol bilong toktok long Tok Pisin.",
        "tok" to "Dispela em wanpela eksampol bilong toktok long Tok Pisin.",
        "lkt" to "Le Lakȟótiyapi eyápi kiŋ owá waŋží hée.",
        "mad" to "Panèka conto tèks sè èlaocaghi bhâsa Madhurâ.",
        "ace" to "Nyoe nakeuh saboh conto teuks nyang geupeugo bak bahsa Acèh.",
        "bbc" to "On ma sada tuladaan ni hata na dipahata do.",
        "bug" to "Iyya'e panessaiwi ada napau ri ogi.",
        "min" to "Iko marupoan conto teks nan diucapan dalam bahaso Minangkabau.",
        "sas" to "Ne contoh teks saq bebase lek base Sasak.",
        "eng_NGA" to "This is a sample of text spoken in Nigerian English.",
        "eng_AUS" to "This is a sample of text spoken in Australian English.",
        "eng_IND" to "This is a sample of text spoken in Indian English.",
        "eng_GBR" to "This is a sample of text spoken in British English.",
        "eng_USA" to "This is a sample of text spoken in American English.",
        "en_GB" to "This is a sample of text spoken in British English.",
        "en_US" to "This is a sample of text spoken in American English.",
        "en_AU" to "This is a sample of text spoken in Australian English.",
        "en_NG" to "This is a sample of text spoken in Nigerian English.",
        "en_IN" to "This is a sample of text spoken in Indian English.",
        "en_JM" to "This is a sample of text spoken in Jamaican English.",
        "en" to "This is a sample of text spoken in English.",
        "spa_USA" to "Esta es una muestra de texto hablado en español estadounidense.",
        "spa_ESP" to "Esta es una muestra de texto hablado en español de España.",
        "es_US" to "Esta es una muestra de texto hablado en español estadounidense.",
        "es_ES" to "Esta es una muestra de texto hablado en español de España.",
        "es_MX" to "Esta es una muestra de texto hablado en español mexicano.",
        "es" to "Esta es una muestra de texto hablado en español.",
        "fra_CAN" to "Ceci est un échantillon de texte parlé en français canadien.",
        "fra_FRA" to "Ceci est un échantillon de texte parlé en français de France.",
        "fr_CA" to "Ceci est un échantillon de texte parlé en français canadien.",
        "fr_FR" to "Ceci est un échantillon de texte parlé en français de France.",
        "fr_BE" to "Ceci est un échantillon de texte parlé en français belge.",
        "fr_CH" to "Ceci est un échantillon de texte parlé en français suisse.",
        "fr" to "Ceci est un échantillon de texte parlé en français.",
        "por_BRA" to "Esta é uma amostra de texto falado em português brasileiro.",
        "por_PRT" to "Esta é uma amostra de texto falado em português de Portugal.",
        "pt_BR" to "Esta é uma amostra de texto falado em português brasileiro.",
        "pt_PT" to "Esta é uma amostra de texto falado em português de Portugal.",
        "pt" to "Esta é uma amostra de texto falado em português.",
        "zho_CHN" to "这是用中国普通话说的文本样本。",
        "zho_TWN" to "這是用台灣國語說的文本樣本。",
        "zh_CN" to "这是用中国普通话说的文本样本。",
        "zh_TW" to "這是用台灣國語說的文本樣本。",
        "zh_HK" to "呢個係用香港粵語講嘅文字樣本。",
        "zh" to "这是用中文说的文本样本。",
        "ru" to "Это образец текста, произнесенного на русском языке.",
        "ru_LV" to "Это образец текста, произнесенного на русском языке в Латвии.",
        "de" to "Dies ist ein Beispieltext in deutscher Sprache.",
        "it" to "Questo è un esempio di testo parlato in italiano.",
        "nl" to "Dit is een voorbeeld van tekst gesproken in het Nederlands.",
        "sv" to "Detta är ett textprov talat på svenska.",
        "pl" to "To jest próbka tekstu mówionego w języku polskim.",
        "el" to "Αυτό είναι ένα δείγμα κειμένου που ομιλείται στα ελληνικά.",
        "hi" to "यह हिंदी में बोले गए पाठ का एक नमूना है।",
        "ja" to "これは日本語で話されたテキストのサンプルです。",
        "ko" to "이것은 한국어로 된 텍스트의 샘플입니다.",
        "ar" to "هذه عينة من نص منطوق باللغة العربية.",
        "he" to "זוהי דוגמה לטקסט מדובר בעברית.",
        "tr" to "Bu, Türkçe konuşulmuş bir metin örneğidir.",
        "th" to "นี่คือตัวอย่างข้อความที่พูดเป็นภาษาไทย",
        "vi" to "Đây là một đoạn văn bản mẫu được nói bằng tiếng Việt Nam.",
        "bn" to "এটি বাংলা ভাষায় কথ্য পাঠ্যের একটি নমুনা।",
        "ur" to "یہ اردو میں بولے گئے متن کا ایک نمونہ ہے۔",
        "fa" to "این یک نمونه از متن گفتاری به زبان فارسی است.",
        "id" to "Ini adalah contoh teks yang diucapkan dalam bahasa Indonesia.",
        "fi" to "Tämä on suomeksi puhuttu tekstinäyte.",
        "hu" to "Ez egy minta a magyar nyelven beszélt szövegből.",
        "cs" to "Toto je vzorek textu mluveného v češtině.",
        "sk" to "Toto je vzorka textu hovoreného v slovenčine.",
        "ro" to "Acesta este un eșantion de text vorbit în română.",
        "uk" to "Це зразок тексту, вимовленого українською мовою.",
        "is" to "Þetta er sýnishorn af texta talað á íslensku.",
        "et" to "See on eesti keeles räägitud teksti näidis.",
        "lv" to "Šis ir latviešu valodā runāta teksta paraugs.",
        "lt" to "Tai pavyzdys teksto, kalbamo lietuvių kalba.",
        "hr" to "Ovo je uzorak teksta govorenog na hrvatskom jeziku.",
        "sr" to "Ово је узорак текста говореног на српском језику.",
        "sl" to "To je vzorec besedila, govorjenega v slovenščini.",
        "bs" to "Ovo je primjer teksta govorenog na bosanskom jeziku.",
        "mk" to "Ова е примерок на текст зборуван на македонски јазик.",
        "bg" to "Това е примерен текст, изговорен на български език.",
        "no" to "Dette er en prøve på tekst talt på norsk.",
        "nb" to "Dette er en prøve på tekst talt på bokmål.",
        "nn" to "Dette er ein prøve på tekst tala på nynorsk.",
        "ca" to "Això és un exemple de text parlat en català.",
        "eu" to "Hau euskaraz hitz egiten den testuaren adibidea da.",
        "gl" to "Este é un exemplo de texto falado en galego.",
        "te" to "ఇది తెలుగులో మాట్లాడిన వచనానికి నమూనా.",
        "ta" to "இது தமிழில் பேசப்பட்ட உரைக்கான மாதிரி.",
        "kn" to "ಇದು ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿದ ಪಠ್ಯದ ಒಂದು ಮಾದರಿ.",
        "pa" to "ਇਹ ਪੰਜਾਬੀ ਵਿੱਚ ਬੋਲਿਆ ਗਿਆ ਪਾਠ ਦਾ ਇੱਕ ਨਮੂਨਾ ਹੈ।",
        "ne" to "यो नेपालीमा बोलिएको पाठको नमूना हो।",
        "ml" to "ഇത് മലയാളത്തിൽ സംസാരിക്കുന്ന ഒരു വാചകത്തിന്റെ മാതൃകയാണ്.",
        "mr" to "हा मराठीत बोलल्या गेलेल्या मजकुराचा नमुना आहे.",
        "gu" to "આ ગુજરાતીમાં બોલાયેલા ટેક્સ્ટનું નમૂનું છે.",
        "si" to "මෙය සිංහල භාෂාවෙන් කථනය කළ පාඨයක ආදර්ශයකි.",
        "or" to "ଏହା ଓଡ଼ିଆରେ କଥିତ ପାଠର ଏକ ନମୁନା।",
        "as" to "এয়া অসমীয়া ভাষাত কোৱা এটা পাঠৰ নমুনা।",
        "km" to "នេះគឺជាគំរូនៃអត្ថបទដែលនិយាយជាភាសាខ្មែរ។",
        "ms" to "Ini ialah contoh teks yang dituturkan dalam bahasa Melayu.",
        "sd" to "هيءَ سنڌي ۾ ڳالهائي وئي ٽيڪسٽ جو هڪ نمونو آهي."
    )
    fun get(iso: String): String = map[iso] ?: ""
}
