"""Generate the R class the way AGP does, so kotlinc can resolve R.

WHY. R is generated at build time from res/, so it exists in no jar and every
`R.drawable.ic_settings` in the app was an `unresolved reference 'R'` in the
local type-check -- 26 of the 27 errors left once the real androidx classpath
was in place, plus one type-inference cascade off the back of them.

WHAT IT BUYS beyond a quieter run: a MISSPELLED resource name in Kotlin becomes
a local compile error. xmlcheck.py resolves references made from XML; nothing
checked the ones made from Kotlin, so `R.drawable.ic_typo` was caught only by
AAPT in CI.

WHAT IT DOES NOT COVER, stated rather than discovered later: resources that come
from a LIBRARY. AAPT merges androidx's own resources into the app's R, so
`R.string.state_on` is legal in the real build and unresolved here. Nothing in
the app uses one today -- the two mentions of `R.string.state_on` and
`R.string.selected` are inside comments in ComposeTheme.kt, describing what the
accessibility delegate says. If one is ever used for real, add it to
LIBRARY_RESOURCES below rather than deleting this checker.

The values are arbitrary: nothing here executes, and AGP's real ids are assigned
at link time anyway.
"""
import os
import re
import sys
import xml.etree.ElementTree as ET

import evpaths

# Resource types that are FOLDERS of files: res/<type>[-qualifier]/<name>.<ext>
FILE_TYPES = ('drawable', 'mipmap', 'layout', 'xml', 'raw', 'anim', 'animator',
              'color', 'menu', 'font', 'transition', 'navigation')

# Tags inside res/values*/ that declare a resource, and the type each declares.
VALUE_TAGS = {
    'string': 'string', 'string-array': 'array', 'integer-array': 'array',
    'array': 'array', 'color': 'color', 'dimen': 'dimen', 'bool': 'bool',
    'integer': 'integer', 'style': 'style', 'plurals': 'plurals',
    'declare-styleable': 'styleable', 'fraction': 'fraction',
}

# Resources the app uses that AAPT merges in from a library rather than from
# res/. Empty today; see the module docstring before adding to it.
LIBRARY_RESOURCES = {}


def sanitize(name):
    """AGP turns '.' and '-' in a resource name into '_' for the R field."""
    return re.sub(r'[.\-]', '_', name)


def collect(main):
    res = os.path.join(main, 'res')
    out = {}

    def add(t, n):
        out.setdefault(t, set()).add(sanitize(n))

    for folder in sorted(os.listdir(res)):
        path = os.path.join(res, folder)
        if not os.path.isdir(path):
            continue
        base = folder.split('-')[0]
        if base in FILE_TYPES:
            for f in sorted(os.listdir(path)):
                add(base, f.split('.')[0])
        if base != 'values':
            # An android:id="@+id/x" anywhere declares an id.
            for f in sorted(os.listdir(path)):
                if not f.endswith('.xml'):
                    continue
                text = open(os.path.join(path, f), encoding='utf-8').read()
                for m in re.finditer(r'@\+id/([A-Za-z0-9_.\-]+)', text):
                    add('id', m.group(1))
            continue
        for f in sorted(os.listdir(path)):
            if not f.endswith('.xml'):
                continue
            try:
                root = ET.parse(os.path.join(path, f)).getroot()
            except ET.ParseError as e:
                # stderr, not stdout: kotlin-typecheck.sh sends this script's
                # stdout to /dev/null, so a message printed there would vanish
                # and the run would die with nothing said.
                print('genr: %s/%s does not parse: %s' % (folder, f, e),
                      file=sys.stderr)
                return None
            for child in root:
                name = child.get('name')
                if not name:
                    continue
                if child.tag == 'item':
                    t = child.get('type')
                    if t:
                        add(t, name)
                    continue
                t = VALUE_TAGS.get(child.tag)
                if t:
                    add(t, name)

    for t, names in LIBRARY_RESOURCES.items():
        for n in names:
            add(t, n)
    return out


def render(package, table):
    lines = ['// GENERATED by tools/check/genr.py -- do not edit, do not commit.',
             '// Stands in for the R class AGP builds from res/ at build time.',
             'package %s' % package, '', 'object R {']
    n = 0x7f010000
    for t in sorted(table):
        lines.append('    object %s {' % t)
        for name in sorted(table[t]):
            n += 1
            lines.append('        const val %s: Int = 0x%08x' % (name, n))
        lines.append('    }')
    lines.append('}')
    return '\n'.join(lines) + '\n'


def main():
    dest = sys.argv[1] if len(sys.argv) > 1 else None
    table = collect(evpaths.main_dir())
    if table is None:
        return 1
    text = render('com.tts.easyvoice', table)
    if dest:
        open(dest, 'w', encoding='utf-8').write(text)
        print('genr: %d types, %d resources -> %s'
              % (len(table), sum(len(v) for v in table.values()), dest))
    else:
        sys.stdout.write(text)
    return 0


if __name__ == '__main__':
    sys.exit(main())
