#!/usr/bin/env bash
# Compile the app AND its instrumented tests with the REAL build -- the same
# Gradle, AGP, Kotlin and Compose compiler plugin CI uses -- and fail on any
# error and on any compiler WARNING from our own sources.
#
# This replaced tools/check/kotlin-typecheck.sh and tools/fetch-deps.py
# (owner, 2026-09-23: "dependency humne khud likhi hai ... usko hatakar jo
# already hai vah kar do"). Those were a hand-built imitation of this build: a
# resolver of our own, an R class generated by our own script, and a bare
# kotlinc diffed against a baseline. The imitation had a real gap -- the resolver
# followed every version it met, not the ones Gradle selects, so it put
# libraries on the classpath the app does not have -- and it never compiled the
# androidTest sources at all, so a mistake there cost a thirteen-minute CI run.
#
# Compiling androidTest also resolves the androidTest classpath, which is where
# AGP's consistent resolution pins every test library to the app's versions.
# That conflict is what kept the accessibility job red through builds 849-857,
# and it is now caught here, before a push.
#
# ZERO WARNINGS is the bar, because it is where the code stands (2026-09-23).
# A new warning is a deprecation or a smell arriving; say why or fix it.
#
# Maven Central answers 429 under load. That is retried; anything else is not.
set -uo pipefail
ROOT=$(cd "$(dirname "$0")/../.." && pwd)
CACHE="$ROOT/tools/.cache"
GV=$(grep -oE "gradle-version: '[0-9.]+'" "$ROOT/.github/workflows/build.yml" | head -1 | grep -oE "[0-9.]+")
GRADLE="$CACHE/gradle-$GV/bin/gradle"
export ANDROID_HOME="$CACHE/android-sdk"
[ -x "$GRADLE" ] && [ -d "$ANDROID_HOME/platforms" ] || {
  echo "gradle-compile  SKIPPED -- Gradle $GV or the Android SDK is missing; run tools/bootstrap.sh"
  exit 0; }

LOG=${TMPDIR:-/tmp}/ev-gradle-compile.log
n=0
while :; do
  (cd "$ROOT" && "$GRADLE" --no-daemon :app:compileDebugKotlin :app:compileDebugAndroidTestKotlin) > "$LOG" 2>&1
  rc=$?
  [ $rc -eq 0 ] && break
  if grep -q " 429 \|status code 429" "$LOG" && [ $n -lt 4 ]; then
    n=$((n + 1)); echo "   Maven Central rate limit (429), retry $n of 4"; sleep $((n * 20)); continue
  fi
  grep -E "^e: |What went wrong" -A6 "$LOG" | head -60
  echo "gradle-compile  FAILED (full log: $LOG)"
  exit 1
done

WARN=$(grep -E "^w: file://$ROOT/app/src/" "$LOG" | sed "s|file://$ROOT/||" | sort -u)
if [ -n "$WARN" ]; then
  echo "$WARN"
  echo "gradle-compile  FAILED -- $(echo "$WARN" | wc -l) compiler warning(s) in our sources"
  exit 1
fi
echo "gradle-compile  app + androidTest compiled with Gradle $GV: 0 errors, 0 warnings"
