package com.sachinbaria.easyvoice
// The sample sentence the Test button speaks, and the one our own engine hands
// back to whoever fires ACTION_GET_SAMPLE_TEXT at us. It is `c3.f0`.
//
// KEYED BY ISO3 AND ONLY BY ISO3. Both callers pass `Locale.getISO3Language()` --
// `GetSampleText` directly, `VoiceRows.speakTest` through `EngineFinder.iso3Of` --
// and that method returns a string of length 3 or of length 0, never anything
// else. Measured rather than assumed: 1,257 calls over every entry of
// `Locale.getAvailableLocales()` and `Locale.getISOLanguages()`, lengths seen
// {0, 3}, zero exceptions.
//
// So the 124 two-letter keys and the 32 `lang_COUNTRY` keys this table carried
// until 2026-09-16 could never be read by anything. They came across with the
// rest of AutoTTS's `f0`, whose key set ours matched exactly -- 340 keys, of
// which 184 were reachable and 156 were not. CLAUDE.md had recorded that those
// 156 were "deliberately not carried"; they were carried, and that note was
// wrong. Deleting them is not a behaviour change of any kind: a map entry whose
// key is never looked up is never consulted.
//
// 49 of the 185 ISO3 codes a scanned voice can produce have no entry here, and
// each of those speaks "Sorry. Sample text for language X is missing." instead
// of demonstrating the voice. Asking the engine itself is the platform's own
// answer to that and is written up in CLAUDE.md; it is the owner's call and it
// would ADD to this file rather than replace it, because the engine's reply is
// optional by contract.
object SampleTexts {
    private val map = mapOf(
        "eng" to "This is a sample of text spoken in English.",
        "spa" to "Esta es una muestra de texto hablado en español.",
        "fra" to "Ceci est un échantillon de texte parlé en français.",
        "deu" to "Dies ist ein Beispieltext in deutscher Sprache.",
        "ita" to "Questo è un esempio di testo parlato in italiano.",
        "por" to "Esta é uma amostra de texto falado em português.",
        "rus" to "Это образец текста, произнесенного на русском языке.",
        "nld" to "Dit is een voorbeeld van tekst gesproken in het Nederlands.",
        "swe" to "Detta är ett textprov talat på svenska.",
        "pol" to "To jest próbka tekstu mówionego w języku polskim.",
        "ell" to "Αυτό είναι ένα δείγμα κειμένου που ομιλείται στα ελληνικά.",
        "hin" to "यह हिंदी में बोले गए पाठ का एक नमूना है।",
        "zho" to "这是用中文说的文本样本。",
        "jpn" to "これは日本語で話されたテキストのサンプルです。",
        "kor" to "이것은 한국어로 된 텍스트의 샘플입니다.",
        "ara" to "هذه عينة من نص منطوق باللغة العربية.",
        "heb" to "זוהי דוגמה לטקסט מדובר בעברית.",
        "tur" to "Bu, Türkçe konuşulmuş bir metin örneğidir.",
        "tha" to "นี่คือตัวอย่างข้อความที่พูดเป็นภาษาไทย",
        "vie" to "Đây là một đoạn văn bản mẫu được nói bằng tiếng Việt Nam.",
        "ben" to "এটি বাংলা ভাষায় কথ্য পাঠ্যের একটি নমুনা।",
        "urd" to "یہ اردو میں بولے گئے متن کا ایک نمونہ ہے۔",
        "fas" to "این یک نمونه از متن گفتاری به زبان فارسی است.",
        "ind" to "Ini adalah contoh teks yang diucapkan dalam bahasa Indonesia.",
        "fin" to "Tämä on suomeksi puhuttu tekstinäyte.",
        "hun" to "Ez egy minta a magyar nyelven beszélt szövegből.",
        "ces" to "Toto je vzorek textu mluveného v češtině.",
        "slk" to "Toto je vzorka textu hovoreného v slovenčine.",
        "ron" to "Acesta este un eșantion de text vorbit în română.",
        "ukr" to "Це зразок тексту, вимовленого українською мовою.",
        "gle" to "Seo sampla de théacs labhartha i nGaeilge.",
        "isl" to "Þetta er sýnishorn af texta talað á íslensku.",
        "est" to "See on eesti keeles räägitud teksti näidis.",
        "lav" to "Šis ir latviešu valodā runāta teksta paraugs.",
        "lit" to "Tai pavyzdys teksto, kalbamo lietuvių kalba.",
        "hrv" to "Ovo je uzorak teksta govorenog na hrvatskom jeziku.",
        "srp" to "Ово је узорак текста говореног на српском језику.",
        "slv" to "To je vzorec besedila, govorjenega v slovenščini.",
        "bos" to "Ovo je primjer teksta govorenog na bosanskom jeziku.",
        "mkd" to "Ова е примерок на текст зборуван на македонски јазик.",
        "bul" to "Това е примерен текст, изговорен на български език.",
        "nno" to "Dette er ein prøve på tekst tala på nynorsk.",
        "nob" to "Dette er en prøve på tekst talt på bokmål.",
        "cat" to "Això és un exemple de text parlat en català.",
        "eus" to "Hau euskaraz hitz egiten den testuaren adibidea da.",
        "glg" to "Este é un exemplo de texto falado en galego.",
        "tel" to "ఇది తెలుగులో మాట్లాడిన వచనానికి నమూనా.",
        "tam" to "இது தமிழில் பேசப்பட்ட உரைக்கான மாதிரி.",
        "kan" to "ಇದು ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿದ ಪಠ್ಯದ ಒಂದು ಮಾದರಿ.",
        "pan" to "ਇਹ ਪੰਜਾਬੀ ਵਿੱਚ ਬੋਲਿਆ ਗਿਆ ਪਾਠ ਦਾ ਇੱਕ ਨਮੂਨਾ ਹੈ।",
        "nep" to "यो नेपालीमा बोलिएको पाठको नमूना हो।",
        "mal" to "ഇത് മലയാളത്തിൽ സംസാരിക്കുന്ന ഒരു വാചകത്തിന്റെ മാതൃകയാണ്.",
        "mar" to "हा मराठीत बोलल्या गेलेल्या मजकुराचा नमुना आहे.",
        "guj" to "આ ગુજરાતીમાં બોલાયેલા ટેક્સ્ટનું નમૂનું છે.",
        "sin" to "මෙය සිංහල භාෂාවෙන් කථනය කළ පාඨයක ආදර්ශයකි.",
        "ori" to "ଏହା ଓଡ଼ିଆରେ କଥିତ ପାଠର ଏକ ନମୁନା।",
        "swa" to "Huu ni mfano wa maandishi yaliyozungumzwa kwa Kiswahili.",
        "zul" to "Lesi isampula sombhalo okhulunywe ngesiZulu.",
        "amh" to "ይህ በአማርኛ የተነገረ የጽሑፍ ናሙና ነው።",
        "yor" to "Eyi jẹ apẹẹrẹ ti ọrọ ti a sọ ni èdè Yorùbá.",
        "ibo" to "Nke a bụ ihe atụ nke okwu a na-asụ n'asụsụ Igbo.",
        "hau" to "Wannan misali ne na rubutun da ake magana a cikin Hausa.",
        "xho" to "Esi sisampula sombhalo othethwayo ngesiXhosa.",
        "som" to "Tani waa tusaale ahaan qoraalka lagu hadlay af Soomaali.",
        "orm" to "Kun fakkeenya barruu afaan Oromoo ta'uun dubbifamu.",
        "msa" to "Ini ialah contoh teks yang dituturkan dalam bahasa Melayu.",
        "tgl" to "Ito ay isang halimbawa ng teksto na sinasalita sa Tagalog.",
        "mon" to "Энэ бол Монгол хэлээр ярьсан текстийн жишээ юм.",
        "khm" to "នេះគឺជាគំរូនៃអត្ថបទដែលនិយាយជាភាសាខ្មែរ។",
        "lao" to "ນີ້ແມ່ນຕົວຢ່າງຂອງຂໍ້ຄວາມທີ່ເວົ້າເປັນພາສາລາວ.",
        "mya" to "ဤသည်မှာ မြန်မာဘာသာဖြင့် ပြောဆိုထားသော စာသားနမူနာတစ်ခုဖြစ်သည်။",
        "kaz" to "Бұл қазақ тілінде сөйленген мәтіннің үлгісі.",
        "uzb" to "Bu o'zbek tilida so'zlashgan matn namunasi.",
        "kir" to "Бул кыргыз тилинде сүйлөнгөн тексттин үлгүсү.",
        "tuk" to "Bu türkmen dilinde gürlenýän tekstiň mysalydyr.",
        "mri" to "He tauira tēnei o te kōrero i te reo Māori.",
        "haw" to "He laʻana kēia o ka ʻōlelo i ka ʻōlelo Hawaiʻi.",
        "smo" to "O lenei o se faʻataʻitaʻiga o le tautala i le gagana Sāmoa.",
        "ton" to "Ko e fakataʻitaʻi ʻeni ʻo e lea faka-Tonga.",
        "alb" to "Kjo është një shembull i tekstit të folur në gjuhën shqipe.",
        "aze" to "Bu, Azərbaycan dilində danışılmış mətn nümunəsidir.",
        "kur" to "Ev nimûneyek ji nivîsê ye ku bi zimanê Kurdî tê axaftin.",
        "pas" to "دا په پښتو ژبه کې د ویل شوي متن یوه نمونه ده.",
        "sot" to "Sena ke mohlala wa mongolo o buuoang ka Sesotho.",
        "asm" to "এয়া অসমীয়া ভাষাত কোৱা এটা পাঠৰ নমুনা।",
        "sun" to "Ieu mangrupikeun conto teks anu diucapkeun dina basa Sunda.",
        "kok" to "हें कोंकणीन उलयिल्ल्या पाठाचो एक नमुनो आसा।",
        "sqi" to "Kjo është një shembull i tekstit të folur në gjuhën shqipe.",
        "mai" to "ई मैथिली में बाजल गेल पाठक एक नमूना अछि।",
        "cmn" to "这是用普通话说的文本样本。",
        "sat" to "नोवा दो सान्ताड़ी ते रोड़ आकान ओलोक् रेनाक् मित् आदोर काना।",
        "snd" to "هيءَ سنڌي ۾ ڳالهائي وئي ٽيڪسٽ جو هڪ نمونو آهي.",
        "kas" to "یہ کاشُر زَبان مَنٛز وَنَل گَے ٹیکسٹُک اَکھ نَمونہ چھُ۔",
        "mni" to "মসি মৈতৈলোন্দা ঙাংখিবা ৱাহৈ পরেংগী খুদম অমনি।",
        "san" to "अयं संस्कृतभाषायां कथितस्य पाठस्य एकं उदाहरणम् अस्ति।",
        "brx" to "बे बर' राव गासैनि सोदोब फरायलाइनि मोनसे बिदिन्थि।",
        "doi" to "एह् डोगरी च बोले गेदे पाठ दा इक नमूना ऐ।",
        "jav" to "Iki conto teks sing diucapake ing basa Jawa.",
        "yue" to "呢個係用粵語講嘅文字樣本。",
        "cym" to "Dyma enghraifft o destun yn cael ei siarad yn Gymraeg.",
        "dan" to "Dette er en prøve af tekst talt på dansk.",
        "fil" to "Ito ay isang halimbawa ng teksto na sinasalita sa Filipino.",
        "lat" to "Hoc exemplum textus lingua Latina locuti est.",
        "afr" to "Dit is 'n voorbeeld van teks wat in Afrikaans gepraat word.",
        "hye" to "Սա հայերենով խոսված տեքստի նմուշ է։",
        "hyw" to "Այս արեւմտահայերէնով խօսուած տեքստի նմուշ է։",
        "kat" to "ეს არის ქართულად ნათქვამი ტექსტის ნიმუში.",
        "ltz" to "Dëst ass e Beispill vun Text dee Lëtzebuergesch geschwat gëtt.",
        "mlt" to "Dan huwa kampjun ta' test mitkellem bil-Malti.",
        "oci" to "Aquò es un exemple de tèxte parlat en occitan.",
        "bre" to "Setu ur skouer eus testenn komzet e brezhoneg.",
        "ina" to "Isto es un exemplo de texto parlate in interlingua.",
        "epo" to "Ĉi tio estas specimeno de teksto parolata en Esperanto.",
        "tgk" to "Ин намунаи матни бо забони тоҷикӣ гуфташуда аст.",
        "bel" to "Гэта ўзор тэксту, прамоўленага на беларускай мове.",
        "gla" to "Seo eisimpleir de theacsa air a bhruidhinn ann an Gàidhlig.",
        "tat" to "Бу татар телендә сөйләнгән текст үрнәге.",
        "chr" to "ᎯᎠ ᎤᎵᎮᎵᏍᏗ ᏗᎧᏃᎩᏍᏗ ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ ᏂᎨᏒᎾ ᎨᏒ.",
        "yid" to "דאָס איז אַ מוסטער פון טעקסט גערעדט אין ייִדיש.",
        "fry" to "Dit is in foarbyld fan tekst sprutsen yn it Frysk.",
        "uig" to "بۇ ئۇيغۇر تىلىدا سۆزلەنگەن تېكىستنىڭ بىر ئۈلگىسى.",
        "lug" to "Kino kye kyakulabirako ky'ebigambo ebyogeddwa mu Luganda.",
        "wol" to "Lii mooy misaal bu benn mbind bu ñuy wax ci wolof.",
        "kin" to "Uru ni urugero rw'inyandiko ivugwa mu Kinyarwanda.",
        "sna" to "Ichi chitsanzo chemutauro unotaurwa muchiShona.",
        "lin" to "Oyo ezali ndakisa ya makomi oyo elobi na lingála.",
        "mlg" to "Ity dia ohatra amin'ny lahatsoratra miteny amin'ny teny Malagasy.",
        "ewe" to "Esia nye kpɔɖeŋu aɖe si wogblɔ le Eʋegbe me.",
        "aka" to "Eyi yɛ nsɛm a wɔka no wɔ Twi kasa mu ho nhwɛso.",
        "nso" to "Se ke mohlala wa sengwalwa seo se boletšwego ka Sepedi.",
        "tsn" to "Se ke sekao sa mokwalo o o buiwang ka Setswana.",
        "nde" to "Lesi yisibonelo sombhalo okhulunywayo ngesiNdebele.",
        "bam" to "Nin ye sɛbɛnni misali ye min bɛ fɔ bamanankan na.",
        "que" to "Kayqa qichwa simipi rimashqa qillqap huknin rikch'aqnin.",
        "grn" to "Ko ha'e peteĩ techapyrã ñe'ẽ ojepurúva guaraníme.",
        "aym" to "Aka aymara arunxa arsuña qillqata uñacht'ayañatakiwa.",
        "bod" to "འདི་ནི་བོད་སྐད་དུ་སྨྲས་པའི་ཡི་གེའི་དཔེ་མཚོན་ཞིག་ཡིན།",
        "dzo" to "འ་ནི་རྫོང་ཁ་ནང་ལབ་མི་ཡིག་ཆ་གི་དཔེ་ཨིན།",
        "tir" to "እዚ ብትግርኛ ዝተዛረበ ጽሑፍ ኣብነት እዩ።",
        "bpy" to "এহান বিষ্ণুপ্রিয়া মণিপুরী ঠারর কথা মাতেসি পাঠর নমুনা।",
        "shn" to "ၼႆႉပဵၼ် တူဝ်ယၢင်ႇ လိၵ်ႈတႆး ဝႃႈ တႆးတႃႇ။",
        "grc" to "Τοῦτό ἐστι παράδειγμα τοῦ λόγου τοῦ λεγομένου ἑλληνιστί.",
        "hat" to "Sa a se yon echantiyon tèks ki pale nan kreyòl ayisyen.",
        "kal" to "Una kalaallisut oqaasiitigut oqaluttup assersuutaavoq.",
        "pap" to "Esaki ta un ehèmpel di teksto papiá na Papiamentu.",
        "jbo" to "ti mupli lo lerpoi poi se cusku bau la lojban.",
        "nci" to "Inin se tlanauatilkayotl tlen motoa ika nauatl.",
        "arg" to "Isto ye un eixemplo de testo charrau en aragonés.",
        "quc" to "We jun k'utb'al tzij pa ri ch'ab'al K'iche'.",
        "lfn" to "Esta es un esemplo de testo parlada en Lingua Franca Nova.",
        "cor" to "Hemm yw ensampel a destenn kewsys yn kernewek.",
        "glv" to "Shoh sampleyr jeh teks loayrit ayns Gaelg.",
        "oss" to "Ай фӕткъуы ирон ӕвзагыл дзургӕ тексты.",
        "che" to "Хӏара нохчийн маттахь дийцина йозанан масал ду.",
        "chv" to "Ку чӑваш чӗлхипе калакан текстӑн тӗслӗхӗ.",
        "sme" to "Dát lea ovdamearka teavsttas mii hállojuvvo davvisámegillii.",
        "smn" to "Taat lii ovdâmerkkâ tekstâst mii sárnojuvvoo anarâškielân.",
        "fao" to "Hetta er eitt dømi um tekst tosaðan á føroyskum.",
        "roh" to "Quai è in exempel dad in text discurrì en rumantsch.",
        "scn" to "Chistu è nu esempiu di testu parratu 'n sicilianu.",
        "vec" to "Questo xe un esempio de testo parlà in vèneto.",
        "lij" to "Questo o l'é un exempio de testo parlou in ligure.",
        "lmo" to "Chest l'è un esempi de test parlaa in lombard.",
        "nds" to "Dit is en Bispeel vun Text, de op Plattdüütsch snackt warrt.",
        "wln" to "Çoula est-st on egzimpe di tecse cåzé e walon.",
        "gsw" to "Des esch e Beispiel vun Tekscht wo uf Elsassisch gschwätzt werd.",
        "als" to "Das isch es Biispil vo Text wo uf Schwizerdütsch gredt wird.",
        "bar" to "Des is a Beispui vo am Text auf Boarisch.",
        "hsb" to "To je přikład teksta rěčaneho w hornjoserbšćinje.",
        "dsb" to "To jo pśikład teksta powědanego w dolnoserbšćinje.",
        "szl" to "To je bajszpil tekstu godanygo we ślůnskij godce.",
        "ckb" to "ئەمە نموونەیەکی دەقی قسەکراوە بە کوردی سۆرانی.",
        "ast" to "Esti ye un exemplu de testu faláu n'asturianu.",
        "sah" to "Бу саха тылынан этиллибит тиэкис холобура.",
        "prg" to "Sta ast ainā prūsiskan bilātan tekstan.",
        "tpi" to "Dispela em wanpela eksampol bilong toktok long Tok Pisin.",
        "tok" to "Dispela em wanpela eksampol bilong toktok long Tok Pisin.",
        "lkt" to "Le Lakȟótiyapi eyápi kiŋ owá waŋží hée.",
        "mad" to "Panèka conto tèks sè èlaocaghi bhâsa Madhurâ.",
        "ace" to "Nyoe nakeuh saboh conto teuks nyang geupeugo bak bahsa Acèh.",
        "bbc" to "On ma sada tuladaan ni hata na dipahata do.",
        "bug" to "Iyya'e panessaiwi ada napau ri ogi.",
        "min" to "Iko marupoan conto teks nan diucapan dalam bahaso Minangkabau.",
        "sas" to "Ne contoh teks saq bebase lek base Sasak."
    )
    fun get(iso: String): String = map[iso] ?: ""
}
